travis:
  secure:
    BINSTAR_TOKEN: MT3vtuGDWr9HGrYVV384Ml+bDL9BbBlY7C/wrjh7FcPl5wffwLa7Vy1t+iQ3dEl1RCGB+u4zuHtLts6UOQ7l7d/u1wkf0nETlipde92vLdFcx3xbDljjXzlpOccgbvVOTnYVk2oK+u6CAF2+a3tYF0OrNSg/b7G5m4sec5vGwTA7i+X5a55skRe8uoRMnpUcZa/iiQ3wEJM4EpErl3ZV/goU5Z1dvyWBr0lb1+joL9yOEHcdxHI4+pAxnC0NRnNqDh9WW3uTngaTM5+BJeuBjRBglwVkoxDyEaEE8r1NmzWTuPa/rLUOgP9JDBhqSSeCPPsGxPf6h05xgs3UUTabseLRyr2/XkfZh7cco2huup0fxu3HA0btDtY3BD4gvZQszyj2a+aFrDvrpWOTiqDTP2AotWE5CYf+IW6qZk0dqczDBSuh9IrrSq/IhT/MowV7wJ/uz1ZL/mVxr4lOsEDp5O2NGjKYhMZjIFjqXExbwMt3VFaWfMWE4cTB6sXQpL8T+6AwWW31p9gDNC/7JVRELTPMz6+RvBUTX2rQAy95E46qffCIjaZ9cr/IpDFC5p37SybnsP0loEZfDRPzVMl00iexj6ZAla52s9NMK1g8uHtV/dbEzgApp2PSr5FTh2vgMGXapDzZtCvPRVJ4vx7hYIgxpev9HPBzI8QGX29Eyck=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
